$(document).on 'click', '.photo-img', ->
  photo = $(this)
  photoSrc = photo.attr('src')
  logoSrc = photo.siblings().find('.company-logo-small').attr('src')
  date = photo.siblings().find('.date').text()
  caption = photo.parent().parent().data("caption")
  subdomain = photo.parent().parent().data("subdomain")
  $('.modal-body').html('<img src=' + photoSrc + '>')
  $('.modal-logo').attr('src', logoSrc)
  $('.modal-logo').parent().attr('href', 'https://' +subdomain + '.jobcrush.co/')
  $('.modal-date').html(date)
  $('.modal-caption').html(caption)
  $('.photo-modal').modal()
